AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  deleteImageS3:
    Properties:
      CodeUri: s3://serverless-app-sam-deleteimages3-20180327/d7065b738ac91fbb6236cd69653b5925
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: serverless-app-photos-20180327
      Handler: deleteImageS3.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::589310877371:role/delete-image-role
      Runtime: python3.6
      Timeout: 15
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
