AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  deleteImageS3:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: deleteImageS3/
      Handler: deleteImageS3.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::589310877371:role/delete-image-role
      Environment:
        Variables:
          BUCKET_NAME: serverless-app-photos-20180327
