AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  deleteImageById:
    Properties:
      CodeUri: s3://serverless-app-sam-20180327/e2c25df6ac9f15a453b128224346596f
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: serveless-app-photos-20180327
          TABLE_NAME: photos
      Events:
        Api:
          Properties:
            Method: delete
            Path: /images/{id}
          Type: Api
      Handler: delete-image-by-id.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::589310877371:role/lambda-dynamodb-access
      Runtime: python3.6
      Timeout: 15
    Type: AWS::Serverless::Function
  getImageById:
    Properties:
      CodeUri: s3://serverless-app-sam-20180327/d53e7db1c841deed13e9e45d89b83a79
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: serveless-app-photos-20180327
          TABLE_NAME: photos
      Events:
        Api:
          Properties:
            Method: get
            Path: /images/{id}
          Type: Api
      Handler: get-image-by-id.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::589310877371:role/lambda-dynamodb-access
      Runtime: python3.6
      Timeout: 15
    Type: AWS::Serverless::Function
  getImages:
    Properties:
      CodeUri: s3://serverless-app-sam-20180327/528e70af1ddbea2b9237d9b9ead28d83
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: serveless-app-photos-20180327
          TABLE_NAME: photos
      Events:
        Api:
          Properties:
            Method: get
            Path: /images
          Type: Api
      Handler: get-images.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::589310877371:role/lambda-dynamodb-access
      Runtime: python3.6
      Timeout: 15
    Type: AWS::Serverless::Function
  postImages:
    Properties:
      CodeUri: s3://serverless-app-sam-20180327/66c3d78365028d32df5a3a517e965636
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: serveless-app-photos-20180327
          TABLE_NAME: photos
      Events:
        Api:
          Properties:
            Method: post
            Path: /images
          Type: Api
      Handler: post-images.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::589310877371:role/lambda-dynamodb-access
      Runtime: python3.6
      Timeout: 15
    Type: AWS::Serverless::Function
  updateImages:
    Properties:
      CodeUri: s3://serverless-app-sam-20180327/a4989aded63e7e3049fd579b93e03dca
      Description: ''
      Environment:
        Variables:
          BUCKET_NAME: serveless-app-photos-20180327
          TABLE_NAME: photos
      Events:
        Api:
          Properties:
            Method: put
            Path: /images
          Type: Api
      Handler: update-image.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::589310877371:role/lambda-dynamodb-access
      Runtime: python3.6
      Timeout: 15
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
